version: '3'

services:
    postgres:
        image: postgres:latest
        container_name: postgres
        env_file:
          - .env
        volumes:
          - ~/desenv/postgres-data:/postgres-data
        ports:
          - "5432:5432"
        networks:
          - rede-code-test
    
    discord-adapter-api:
        image: dbmacedo/code-test-discord:discord-adapter-api
        container_name: discord-adapter-api
        env_file:
          - .env
        ports:
          - "8080:8080"
        networks:
          - rede-code-test
    
    code-test-api:
        image: dbmacedo/code-test-discord:code-test-api
        container_name: code-test-api
        env_file:
          - .env
        ports:
          - "8081:8081"
        networks:
          - rede-code-test      

networks:
  rede-code-test:
    driver: bridge
